=== Smith-Coder-2000/HMS-Accounts-Module/hms_account.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="hospital">
<xs:complexType>
<xs:sequence>
<xs:element name="patient" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="bill_id" type="xs:integer"></xs:element>
<xs:element name="Name" type="xs:string"></xs:element>
<xs:element name="type" type="xs:string"></xs:element>
<xs:element name="bill_amount" type="custype2"></xs:element>
<xs:element name="status" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
<xs:unique name="testUnique">
      <xs:selector xpath="patient"/>
      <xs:field xpath="bill_id"/>
 </xs:unique>
</xs:element>
<xs:simpleType name="custype2">
<xs:restriction base="xs:integer">
<xs:minInclusive value="500"></xs:minInclusive>
<xs:maxInclusive value="1000000"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
</xs:schema>

=== Smith-Coder-2000/HMS-Accounts-Module/hms_account.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hms_account.xsl"?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="hms_account.xsd">
  <patient>
  	<bill_id>01</bill_id>
    <Name>Dohni</Name>
    <type>IN_Patient</type>
    <bill_amount>30000</bill_amount>
    <status>Complete</status>
  </patient>
  <patient>
    <bill_id>02</bill_id>
    <Name>Kohli</Name>
    <type>IN_Patient</type>
    <bill_amount>20000</bill_amount>
    <status>Pending</status>
  </patient>
  <patient>
   	<bill_id>03</bill_id>
    <Name>Rahul</Name>
    <type>OUT_Patient</type>
    <bill_amount>10000</bill_amount>
    <status>Pending</status>
  </patient>
  <patient>
   	<bill_id>04</bill_id>
    <Name>Karthik</Name>
    <type>IN_Patient</type>
    <bill_amount>90000</bill_amount>
    <status>Complete</status>
  </patient>
  <patient>
   	<bill_id>05</bill_id>
    <Name>Dinesh</Name>
    <type>IN_Patient</type>
    <bill_amount>20000</bill_amount>
    <status>Pending</status>
  </patient>
  <patient>
   	<bill_id>06</bill_id>
    <Name>Danush</Name>
    <type>OUT_Patient</type>
    <bill_amount>30000</bill_amount>
    <status>Complete</status>
  </patient>
  <patient>
   	<bill_id>07</bill_id>
    <Name>Yash</Name>
    <type>IN_Patient</type>
    <bill_amount>90000</bill_amount>
    <status>Complete</status>
  </patient>
  <patient>
   	<bill_id>08</bill_id>
    <Name>Raj</Name>
    <type>IN_Patient</type>
    <bill_amount>60000</bill_amount>
    <status>Pending</status>
  </patient>
  <patient>
   	<bill_id>09</bill_id>
    <Name>Phantom</Name>
    <type>OUT_Patient</type>
    <bill_amount>70000</bill_amount>
    <status>Pending</status>
  </patient>
  <patient>
   	<bill_id>10</bill_id>
    <Name>Rocky</Name>
    <type>OUT_Patient</type>
    <bill_amount>75000</bill_amount>
    <status>Complete</status>
  </patient>
</hospital>
